"""SocialFUX backend regression tests."""
import io
import os
import time

import pytest
import requests

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "https://fux-staging.preview.emergentagent.com").rstrip("/")
API = f"{BASE_URL}/api"

ADMIN_EMAIL = "admin@socialfux.local"
ADMIN_PASSWORD = "admin123456"


# ---------------- Fixtures ----------------
@pytest.fixture(scope="session")
def api_client():
    s = requests.Session()
    s.headers.update({"Content-Type": "application/json"})
    return s


@pytest.fixture(scope="session")
def auth_token(api_client):
    r = api_client.post(f"{API}/auth/login", json={"email": ADMIN_EMAIL, "password": ADMIN_PASSWORD})
    assert r.status_code == 200, f"Login failed: {r.status_code} {r.text}"
    return r.json()["access_token"]


@pytest.fixture(scope="session")
def auth_client(api_client, auth_token):
    s = requests.Session()
    s.headers.update({"Content-Type": "application/json", "Authorization": f"Bearer {auth_token}"})
    return s


# ---------------- Auth ----------------
class TestAuth:
    def test_login_success(self, api_client):
        r = api_client.post(f"{API}/auth/login", json={"email": ADMIN_EMAIL, "password": ADMIN_PASSWORD})
        assert r.status_code == 200
        data = r.json()
        assert "access_token" in data
        assert data["user"]["email"] == ADMIN_EMAIL
        assert data["user"]["role"] == "superadmin"

    def test_login_bad_credentials(self, api_client):
        r = api_client.post(f"{API}/auth/login", json={"email": ADMIN_EMAIL, "password": "wrong"})
        assert r.status_code == 401

    def test_protected_requires_auth(self, api_client):
        r = api_client.get(f"{API}/customers")
        assert r.status_code in (401, 403)


# ---------------- Settings & Dashboard ----------------
class TestMeta:
    def test_settings(self, auth_client):
        r = auth_client.get(f"{API}/settings")
        assert r.status_code == 200
        data = r.json()
        assert data["app"] == "SocialFUX"
        assert "version" in data
        assert "domain" in data
        assert data["llm_configured"] is True

    def test_dashboard_stats(self, auth_client):
        r = auth_client.get(f"{API}/dashboard/stats")
        assert r.status_code == 200
        data = r.json()
        assert data.get("customers_count", 0) >= 1
        assert "latest_news" in data
        assert "latest_generated_content" in data
        assert isinstance(data["latest_news"], list)


# ---------------- Customers ----------------
class TestCustomers:
    _created_id = None

    def test_list_customers_has_seed(self, auth_client):
        r = auth_client.get(f"{API}/customers")
        assert r.status_code == 200
        data = r.json()
        assert isinstance(data, list) and len(data) >= 1
        names = [c.get("name", "") for c in data]
        assert any("TuningFux" in n for n in names), f"Seeded customer missing. Got: {names}"

    def test_create_customer(self, auth_client):
        payload = {
            "name": "TEST_Customer_Regression",
            "website": "https://test-example.com",
            "services": ["chiptuning", "dpf"],
        }
        r = auth_client.post(f"{API}/customers", json=payload)
        assert r.status_code in (200, 201), r.text
        data = r.json()
        assert data["name"] == payload["name"]
        assert data.get("slug"), "slug should be autogenerated"
        TestCustomers._created_id = data["id"]

        # verify via GET
        g = auth_client.get(f"{API}/customers/{data['id']}")
        assert g.status_code == 200
        assert g.json()["name"] == payload["name"]

    def test_update_customer(self, auth_client):
        assert TestCustomers._created_id
        r = auth_client.put(
            f"{API}/customers/{TestCustomers._created_id}",
            json={"website": "https://updated.example.com"},
        )
        assert r.status_code == 200, r.text
        assert r.json()["website"] == "https://updated.example.com"

    def test_upload_logo(self, auth_client):
        assert TestCustomers._created_id
        # 1x1 PNG bytes
        png = (
            b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01"
            b"\x08\x06\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\rIDATx\x9cc\xf8\xcf"
            b"\xc0\x00\x00\x00\x03\x00\x01\xd3\xd1\x0b\xe6\x00\x00\x00\x00IEND\xaeB`\x82"
        )
        files = {"file": ("logo.png", io.BytesIO(png), "image/png")}
        headers = {"Authorization": auth_client.headers["Authorization"]}
        r = requests.post(
            f"{API}/customers/{TestCustomers._created_id}/logo",
            files=files,
            headers=headers,
        )
        assert r.status_code == 200, r.text
        data = r.json()
        assert data.get("logo_path", "").startswith("/uploads/")
        # static served
        static = requests.get(BASE_URL + data["logo_path"])
        assert static.status_code == 200

    def test_delete_customer(self, auth_client):
        assert TestCustomers._created_id
        r = auth_client.delete(f"{API}/customers/{TestCustomers._created_id}")
        assert r.status_code in (200, 204)
        g = auth_client.get(f"{API}/customers/{TestCustomers._created_id}")
        assert g.status_code == 404


# ---------------- News sources ----------------
class TestNewsSources:
    _src_id = None

    def test_list_seeded(self, auth_client):
        r = auth_client.get(f"{API}/news-sources")
        assert r.status_code == 200
        data = r.json()
        assert len(data) >= 7, f"expected >=7 seeded sources, got {len(data)}"

    def test_create_source(self, auth_client):
        payload = {"name": "TEST_Source", "url": "https://example.com", "rss_url": "https://example.com/rss"}
        r = auth_client.post(f"{API}/news-sources", json=payload)
        assert r.status_code in (200, 201), r.text
        TestNewsSources._src_id = r.json()["id"]

    def test_fetch_missing_rss_graceful(self, auth_client):
        # Create source with unreachable rss
        r = auth_client.post(f"{API}/news-sources", json={
            "name": "TEST_Broken", "url": "https://invalid.invalid", "rss_url": "https://invalid.invalid/rss.xml"
        })
        assert r.status_code in (200, 201)
        sid = r.json()["id"]
        f = auth_client.post(f"{API}/news-sources/{sid}/fetch")
        assert f.status_code == 200, f"Fetch should not crash: {f.status_code} {f.text}"
        data = f.json()
        assert "imported" in data
        # cleanup
        auth_client.delete(f"{API}/news-sources/{sid}")

    def test_cleanup_source(self, auth_client):
        if TestNewsSources._src_id:
            auth_client.delete(f"{API}/news-sources/{TestNewsSources._src_id}")


# ---------------- News items ----------------
class TestNewsItems:
    _item_id = None

    def test_import_url(self, auth_client):
        url = "https://www.auto-motor-und-sport.de/"
        r = auth_client.post(f"{API}/news-items/import-url", json={"url": url})
        assert r.status_code in (200, 201), r.text
        data = r.json()
        assert data.get("source_url") == url or data.get("url") == url or url in str(data)
        TestNewsItems._item_id = data.get("id")

    def test_import_url_duplicate(self, auth_client):
        url = "https://www.auto-motor-und-sport.de/"
        r = auth_client.post(f"{API}/news-items/import-url", json={"url": url})
        assert r.status_code in (200, 201)

    def test_list_news_items_filter(self, auth_client):
        r = auth_client.get(f"{API}/news-items", params={"status": "new"})
        assert r.status_code == 200
        assert isinstance(r.json(), list)


# ---------------- Generator ----------------
class TestGenerator:
    _customer_id = None
    _content_id = None

    def test_get_customer(self, auth_client):
        r = auth_client.get(f"{API}/customers")
        assert r.status_code == 200
        TestGenerator._customer_id = r.json()[0]["id"]

    def test_generate_content(self, auth_client):
        assert TestGenerator._customer_id
        payload = {
            "customer_id": TestGenerator._customer_id,
            "platform": "instagram",
            "tone": "professional",
            "cta": "Jetzt Termin sichern",
        }
        r = auth_client.post(f"{API}/generator/content", json=payload, timeout=90)
        assert r.status_code in (200, 201), r.text
        data = r.json()
        assert data.get("title"), f"Empty title: {data}"
        assert data.get("body"), "empty body"
        assert isinstance(data.get("hashtags", []), list)
        TestGenerator._content_id = data.get("id")

    def test_hashtags(self, auth_client):
        r = auth_client.post(f"{API}/generator/hashtags", json={"text": "Chiptuning und DPF Service", "count": 5}, timeout=60)
        assert r.status_code == 200, r.text
        tags = r.json()
        # Accept either list or dict wrapper
        if isinstance(tags, dict):
            tags = tags.get("hashtags", [])
        assert isinstance(tags, list) and len(tags) > 0
        assert all(str(t).startswith("#") for t in tags), tags

    def test_compliance_check_illegal(self, auth_client):
        r = auth_client.post(
            f"{API}/generator/compliance-check",
            json={"text": "Wir bieten 100% legal DPF off und TÜV garantiert"},
        )
        assert r.status_code == 200
        data = r.json()
        assert data.get("ok") is False
        assert data.get("warnings") or data.get("issues")

    def test_list_generated_contents(self, auth_client):
        r = auth_client.get(f"{API}/generator/contents")
        assert r.status_code == 200
        assert isinstance(r.json(), list)

    def test_update_generated_content(self, auth_client):
        if not TestGenerator._content_id:
            pytest.skip("no content id")
        r = auth_client.put(
            f"{API}/generator/contents/{TestGenerator._content_id}",
            json={"status": "approved"},
        )
        assert r.status_code == 200, r.text
        assert r.json().get("status") == "approved"


# ---------------- Creatives ----------------
class TestCreatives:
    _creative_id = None
    _customer_id = None

    def test_create_creative(self, auth_client):
        r = auth_client.get(f"{API}/customers")
        cust = r.json()[0]
        TestCreatives._customer_id = cust["id"]
        payload = {
            "customer_id": cust["id"],
            "headline": "TEST Headline",
            "subline": "TEST Subline",
            "cta": "Book now",
            "format": "1080x1080",
        }
        c = auth_client.post(f"{API}/creatives", json=payload)
        assert c.status_code in (200, 201), c.text
        data = c.json()
        TestCreatives._creative_id = data["id"]
        assert "preview_html" in data
        assert "TEST Headline" in data["preview_html"]

    def test_list_creatives(self, auth_client):
        r = auth_client.get(f"{API}/creatives")
        assert r.status_code == 200
        assert isinstance(r.json(), list)

    def test_update_creative(self, auth_client):
        assert TestCreatives._creative_id
        r = auth_client.put(
            f"{API}/creatives/{TestCreatives._creative_id}",
            json={"headline": "UPDATED Headline"},
        )
        assert r.status_code == 200, r.text
        assert "UPDATED Headline" in r.json()["preview_html"]

    def test_export_png(self, auth_client):
        assert TestCreatives._creative_id
        r = auth_client.post(f"{API}/creatives/{TestCreatives._creative_id}/export-png")
        assert r.status_code == 200, r.text
        assert r.json()["image_path"].endswith(".png")

    def test_delete_creative(self, auth_client):
        assert TestCreatives._creative_id
        r = auth_client.delete(f"{API}/creatives/{TestCreatives._creative_id}")
        assert r.status_code in (200, 204)


# ---------------- Templates ----------------
class TestTemplates:
    def test_list_seeded(self, auth_client):
        r = auth_client.get(f"{API}/templates")
        assert r.status_code == 200
        data = r.json()
        assert len(data) >= 3, f"expected >=3 templates, got {len(data)}"

    def test_crud(self, auth_client):
        payload = {"name": "TEST_Template", "format": "1080x1080", "html": "<div>test</div>"}
        r = auth_client.post(f"{API}/templates", json=payload)
        assert r.status_code in (200, 201), r.text
        tid = r.json()["id"]
        u = auth_client.put(f"{API}/templates/{tid}", json={"name": "TEST_Template_Updated"})
        assert u.status_code == 200
        assert u.json()["name"] == "TEST_Template_Updated"
        d = auth_client.delete(f"{API}/templates/{tid}")
        assert d.status_code in (200, 204)
